spring.jpa:
  database: POSTGRESQL
  hibernate.ddl-auto: update
  show-sql: true

spring.datasource:
  driverClassName: org.postgresql.Driver
  url: jdbc:postgresql://localhost:5432/test
  username: postgres
  password: password

spring.flyway:
  user: postgres
  password: password
  schemas: post
  enabled: true
  locations: classpath:db/migration
